<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.5.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.WsFederation" Version="10.0.8" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.19.1" />
    <PackageReference Include="SFA.DAS.Configuration.AzureTableStorage" Version="17.1.165" />
    <PackageReference Include="SFA.DAS.DfESignIn.Auth" Version="17.1.165" />
    <PackageReference Include="SFA.DAS.Provider.Shared.UI" Version="2.0.57" />
    <PackageReference Include="SFA.DAS.ProviderUrlHelper" Version="17267.0.559" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="10.0.8" />
  </ItemGroup>

  <!--Transitive Packages-->
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.OData" Version="5.8.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.Roatp.ProviderModeration.Application\SFA.DAS.Roatp.ProviderModeration.Application.csproj" />
    <ProjectReference Include="..\SFA.DAS.Roatp.ProviderModeration.Infrastructure\SFA.DAS.Roatp.ProviderModeration.Infrastructure.csproj" />
  </ItemGroup>

</Project>
